# Generated by Django 5.2.1 on 2025-05-20 08:54

import colorfield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_product_feature_product_features'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productcolor',
            name='hex_code',
            field=colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='رنگ'),
        ),
    ]
