# Generated by Django 5.2.1 on 2025-05-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_productcolor_hex_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='has_color_price_variation',
            field=models.BooleanField(default=False, verbose_name='قیمت هر رنگ متفاوت است؟'),
        ),
        migrations.AddField(
            model_name='productcolor',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت رنگ خاص'),
        ),
    ]
