# Generated by Django 5.2.1 on 2025-05-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_product_has_color_price_variation_productcolor_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productcolor',
            name='extra_price',
        ),
    ]
