# Generated by Django 5.2.1 on 2025-05-20 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_productcolor_extra_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='has_color_price_variation',
            field=models.BooleanField(default=False, verbose_name='قیمت رنگ\u200cها متفاوت است؟'),
        ),
    ]
